# YAML anchors
shared:

  # Task : sync and merge with rsync 2 rep. Used to merge stack and config
  - &merge-stack-and-config
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: cycloid/cycloid-toolkit
        tag: latest
    run:
      path: /usr/bin/merge-stack-and-config
    outputs:
    - name: merged-stack
      path: "merged-stack"

  # Task : connect on the bastion server and run ansible from it
  - &run-ansible-from-bastion
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cycloid/cycloid-toolkit
          tag: "v((ansible_version))"
      run:
        path: /usr/bin/ansible-runner
      caches:
        - path: ansible-playbook/roles
      inputs:
      - name: merged-stack
        path: ansible-playbook

  - &aws-ami-cleaner
    task: aws-ami-cleaner
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cycloid/cycloid-toolkit
          tag: "v((ansible_version))"
      run:
        path: /usr/bin/aws-ami-cleaner
      params:
        AWS_ACCESS_KEY_ID: ((aws_access_key))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
        AWS_DEFAULT_REGION: ((aws_default_region))
        KEEP: 3
        AWS_NAME_PATTERNS: >
                  [
                    "((customer))_((project))_front_((env))"
                  ]

groups:

- name: overview
  jobs:
  - application-deployment
  - terraform-plan
  - terraform-apply
  - build-ami-front
  - build-application
  - functional-tests
- name: application
  jobs:
  - application-deployment
  - build-application
  - functional-tests

- name: infra
  jobs:
  - terraform-plan
  - terraform-apply
  - build-ami-front

- name: destroy
  jobs:
  - terraform-destroy

resource_types:

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: '0.12.19'

- name: packer
  type: docker-image
  source:
    repository: jdub/packer-resource

resources:

- name: tfstate
  type: terraform
  icon: terraform
  source:
    env_name: ((env))
    backend_type: s3
    backend_config:
      bucket: ((terraform_storage_bucket_name))
      key: ((project))-((env)).tfstate
      workspace_key_prefix: ((project))
      region: ((aws_default_region))
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
    vars:
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
      env: ((env))
      project: ((project))
      customer: ((customer))
      aws_region: ((aws_default_region))
      rds_password: ((rds_password))
      deploy_bucket_name: ((deploy_bucket_name))
    env:
      AWS_ACCESS_KEY_ID: ((aws_access_key))
      AWS_DEFAULT_REGION: ((aws_default_region))
      AWS_SECRET_ACCESS_KEY: ((aws_secret_key))

# The Pipeline stack (will be merged with the config)
- name: git_stack-pipeline
  icon: github-circle
  type: git
  source:
    uri: https://github.com/cycloid-community-catalog/stack-lemp
    branch: ((stack_git_branch))
    paths:
      - pipeline/*

# The Terraform stack (will be merged with the config)
- name: git_stack-terraform
  icon: github-circle
  type: git
  source:
    uri: https://github.com/cycloid-community-catalog/stack-lemp
    branch: ((stack_git_branch))
    paths:
      - terraform/*

# The config (will be merged with the stack), mainly used for pipeline files
- name: git_config
  type: git
  icon: github-circle
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))

# The Terraform config (will be merged with the stack)
- name: git_config-terraform
  type: git
  icon: github-circle
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((config_terraform_path))/*

# The Ansible stack (will be merged with the config)
- name: git_stack-ansible
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cycloid-community-catalog/stack-lemp
    branch: ((stack_git_branch))
    paths:
      - ansible/*

# The Ansible config (will be merged with the stack)
- name: git_config-ansible
  type: git
  icon: github-circle
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((config_ansible_path))/environments/((env))-*

#
# application
#
- name: git_app-code
  type: git
  icon: github-circle
  source:
    uri: ((lemp_git_repository))
    branch: ((lemp_git_branch))
    private_key: ((lemp_git_private_key))

- name: s3_app-release
  type: s3
  icon: aws
  source:
    bucket: ((deploy_bucket_name))
    versioned_file: ((deploy_bucket_object_path))
    private: true
    region_name: ((aws_default_region))
    access_key_id: ((aws_access_key))
    secret_access_key: ((aws_secret_key))
    skip_download: true

# The AMI builder for the front servers (for ASG scale-up)
- name: ami_front
  type: packer
  source:
    aws_access_key_id: ((aws_access_key))
    aws_secret_access_key: ((aws_secret_key))
    region: ((aws_default_region))

jobs:

# Build a new AMI whenever there is a change in Ansible
- name: build-ami-front
  serial: True
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - do:
    - get: git_stack-ansible
      params: {depth: 1}
      trigger: true
    - get: git_config-ansible
      params: {depth: 1}
      trigger: true

    - task: merge-stack-and-config
      config:
        <<: *merge-stack-and-config
        inputs:
        - name: git_config-ansible
          path: "config"
        - name: git_stack-ansible
          path: "stack"
      params:
        CONFIG_PATH: ((config_ansible_path))
        STACK_PATH: ansible
        EXTRA_ANSIBLE_VARS:
          deploy_bucket_object_path: ((deploy_bucket_object_path))
          deploy_bucket_name: ((deploy_bucket_name))
          aws_default_region: ((aws_default_region))
          rds_password: ((rds_password))

    - put: ami_front
      params:
        inventory_groups: tag_role_front,tag_project_((project)),tag_env_((env))
        env: ((env))
        customer: ((customer))
        project: ((project))
        role: front
        public_key: ((debug_public_key))
        vault_password: ((ansible_vault_password))
        skip_tags: deploy,notforbuild
        template: merged-stack/packer/front/packer_template.json
        var_file: merged-stack/packer/front/secrets.json
        aws_access_key_id: ((aws_admin.access_key))
        aws_secret_access_key: ((aws_admin.secret_key))
        aws_region: ((aws_default_region))
        ansible_version: ((ansible_version))
        packer_instance_type: t3.small

# Merge and trigger a plan whenever there is a commit in Terraform stack or config
- name: terraform-plan
  serial: True
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_stack-terraform
        params: {depth: 1}
        trigger: true
      - get: git_config-terraform
        params: {depth: 1}
        trigger: true
      - get: ami_front
        passed: [build-ami-front]
        trigger: true

      - task: merge-stack-and-config
        config:
          <<: *merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
        params:
          CONFIG_PATH: ((config_terraform_path))
          STACK_PATH: terraform

      - put: tfstate
        params:
          plan_only: true
          terraform_source: merged-stack/

# Merge and trigger an apply manually (no autostart of this job)
- name: terraform-apply
  serial: True
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_stack-terraform
        trigger: false
        passed:
          - terraform-plan
      - get: git_config-terraform
        trigger: false
        passed:
          - terraform-plan
      - get: tfstate
        trigger: false
        passed:
          - terraform-plan

      - task: merge-stack-and-config
        config:
          <<: *merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
        params:
          CONFIG_PATH: ((config_terraform_path))
          STACK_PATH: terraform

      - put: tfstate
        params:
          plan_run: true
          terraform_source: merged-stack/

      - *aws-ami-cleaner

- name: terraform-destroy
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
        - get: git_stack-terraform
          params: {depth: 1}
          trigger: false
        - get: git_config-terraform
          params: {depth: 1}
          trigger: false
        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: git_config-terraform
              path: "config"
            - name: git_stack-terraform
              path: "stack"
          params:
            CONFIG_PATH: ((config_terraform_path))
            STACK_PATH: terraform

        - put: tfstate
          params:
            action: destroy
            terraform_source: merged-stack/
          get_params:
            action: destroy

########################################################################### Code

# Generate the release whenever there is a commit on the code
- name: build-application
  max_in_flight: 1
  serial: True
  build_logs_to_retain: 10
  plan:
  - do:
    - get: git_app-code
      params: {depth: 1}
      trigger: true
    - get: git_config
      params: {depth: 1}
      trigger: false
    - get: git_stack-pipeline
      params: {depth: 1}
      trigger: false

    - task: merge-stack-and-config
      config:
        <<: *merge-stack-and-config
        inputs:
        - name: git_config
          path: "config"
        - name: git_stack-pipeline
          path: "stack"
      params:
        CONFIG_PATH: ((config_pipeline_path))
        STACK_PATH: pipeline

    - task: build-release
      file: merged-stack/build-release.yml
      params:
        rds_password: ((rds_password))
        env: ((env))

    - put: s3_app-release
      params:
        acl: private
        file: release/s3_app-release.tar.gz

#
# Front deploy
#

- name: application-deployment
  serial: True
  build_logs_to_retain: 10
  plan:
  - do:
    - get: git_stack-ansible
      params: {depth: 1}
      trigger: false

    - get: git_config-ansible
      params: {depth: 1}
      trigger: false

    - get: s3_app-release
      passed:
        - build-application
      trigger: true

    - get: tfstate
      passed:
        - terraform-apply
      trigger: false

    - get: git_app-code
      params: {depth: 1}
      passed: [build-application]
      trigger: false

    - task: merge-stack-and-config
      config:
        <<: *merge-stack-and-config
        inputs:
        - name: git_config-ansible
          path: "config"
        - name: git_stack-ansible
          path: "stack"
        - name: tfstate
          path: "terraform"
      params:
        CONFIG_PATH: ((config_ansible_path))
        STACK_PATH: ansible

    - task: run-ansible
      <<: *run-ansible-from-bastion
      params:
        SSH_JUMP_URL: ((bastion_url))
        SSH_PRIVATE_KEY: ((bastion_private_key_pair))
        ANSIBLE_VAULT_PASSWORD: ((ansible_vault_password))
        AWS_DEFAULT_REGION: ((aws_default_region))
        AWS_ACCESS_KEY_ID: ((aws_access_key))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
        ANSIBLE_PLAYBOOK_PATH: ansible-playbook
        ANSIBLE_PLAYBOOK_NAME: lemp.yml
        ANSIBLE_FORCE_GALAXY: false
        EXTRA_ANSIBLE_VARS:
          customer: ((customer))
          project: ((project))
          env: ((env))
          default_ec2_region: ((aws_default_region))
          aws_default_region: ((aws_default_region))
          deploy_bucket_object_path: ((deploy_bucket_object_path))
          deploy_bucket_name: ((deploy_bucket_name))
          rds_password: ((rds_password))
        TAGS:
          - deploy

- name: functional-tests
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - do:
    - get: s3_app-release
      trigger: true
      passed: [application-deployment]
    - get: git_app-code
      params: {depth: 1}
      passed: [application-deployment]
      trigger: false

    - get: git_config
      params: {depth: 1}
      trigger: false
    - get: git_stack-pipeline
      params: {depth: 1}
      trigger: false

    - task: merge-stack-and-config
      config:
        <<: *merge-stack-and-config
        inputs:
        - name: git_config
          path: "config"
        - name: git_stack-pipeline
          path: "stack"
      params:
        CONFIG_PATH: ((config_pipeline_path))
        STACK_PATH: pipeline

    - task: run
      file: merged-stack/functional-tests.yml
      params:
        env: ((env))
