---

#
# Front
#
- hosts: tag_role_front:&tag_project_{{project}}:&tag_env_{{ env }}:!tag_packer_build_true
  become: yes
  serial: 100%

  vars:
    # variable set by userdata or via the pipeline
    env_variables:
      RDS_ADDRESS: "{{ rds_address | default('empty', True) }}"
      RDS_PORT: "{{ rds_port | default('empty', True) }}"
      RDS_DATABASE: "{{ rds_database | default('empty', True) }}"
      RDS_USERNAME: "{{ rds_username | default('empty', True) }}"
      RDS_PASSWORD: "{{ rds_password | default('empty', True) }}"
      S3_MEDIAS: "{{ s3_medias | default('empty', True) }}"
      ELASTICACHE_ADDRESS: "{{ elasticache_address | default('empty', True) }}"

  vars_files:
    - "environments/default_front.yml"
    - [ "environments/{{ env }}-front.yml", "environments/empty.yml" ]
    - [ "environments/{{ env }}-secrets.yml", "environments/empty.yml" ]

  pre_tasks:
    - name: Restart fluentd to use the hostname on boot
      service:
        name: td-agent
        state: restarted
      tags:
        - notforbuild
        - molecule-notest


    - name: Add environments variables
      copy:
        content: "{% for key, value in env_variables.items() %}export {{key}}='{{value}}'\n{% endfor %}"
        dest: "/etc/environment"
        owner: root
        group: root
      tags:
        - php
        - deploy
        - notforbuild

    - name: Ensure php fpm pool.d directory exist
      file:
        path: /etc/php/{{ php_version_to_install }}/fpm/pool.d
        state: directory
        mode: 0755
      tags:
        - php

    - name: Add fpm environments variables
      copy:
        content: "[{{ ansistrano_user }}]\n{% for key, value in env_variables.items() %}  env[{{key}}] = '{{value}}'\n{% endfor %}"
        dest: "/etc/php/{{ php_version_to_install }}/fpm/pool.d/env_variables.conf"
        owner: root
        group: root
      tags:
        - php
        - deploy
        - notforbuild

    - name: Imported tasks
      import_tasks: tasks.yml

  roles:
    - role: cycloid.base-aws
    - role: cycloid.customer-ssh
      home_directory: "/home/{{ ansistrano_user }}"
      user: "{{ ansistrano_user }}"
      tags: team-ssh
    #- role: cycloid.postfix
    #  tags:
    #    - postfix
    #    - runatboot
    - role: cycloid.php
      tags:
        - php
        - runatboot

    #
    # Application DEPLOY
    #
    - role: cycloid.deployment
      tags:
        - notforbuild
        - deploy

    - role: jdauphant.nginx
      tags:
        - nginx

    - role: cycloid.cron
      tags:
        - cron
        - notforbuild

    - role: cycloid.telegraf
      tags:
        - telegraf
      when: telegraf_install


    - {role: cycloid.fluentd, tags: fluentd}
  tags:
    - front
